service: cardToken

useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x

functions:
  cardToken:
    handler: src/index.cardToken
    events:
      - httpApi: POST /tokens

  GetDataCardByToken:
    handler: src/index.GetDataCardByToken
    events:
      - httpApi: 
          method: GET
          path: /tokens

plugins:
  - serverless-esbuild
  - serverless-offline